# Generated by Django 5.2.1 on 2025-11-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_full_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": (
                    ("can_download_logs", "Може завантажувати журнали DOMINIUM"),
                )
            },
        ),
    ]
