# Generated by Django 5.2.1 on 2025-10-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="featured_homepage",
            field=models.BooleanField(
                default=False,
                help_text="Відзначте, щоб показувати об'єкт у блоці «Топ 3» на головній сторінці.",
            ),
        ),
        migrations.CreateModel(
            name="HomepageHighlightSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limit",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Скільки об'єктів показувати на головній (використовується, якщо недостатньо ручного вибору).",
                    ),
                ),
                (
                    "price_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Мінімальна ціна (USD). Залиште порожнім, щоб не обмежувати.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Максимальна ціна (USD). Залиште порожнім, щоб не обмежувати.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "region_keyword",
                    models.CharField(
                        blank=True,
                        help_text="Ключове слово/район для пошуку в адресі (наприклад, «Київ», «Поділ»).",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Якщо обрано — підбірка буде обмежена цими типами нерухомості.",
                        to="house.propertytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Налаштування головної підбірки",
                "verbose_name_plural": "Налаштування головної підбірки",
            },
        ),
    ]
