# Generated by Django 5.2.1 on 2025-11-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0002_property_featured_homepage_homepagehighlightsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
