# Generated by Django 5.2.1 on 2025-11-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0004_propertyimage_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyimage",
            options={"ordering": ["sort_order", "-id"]},
        ),
    ]
