# Generated by Django 5.2.1 on 2025-11-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0005_alter_propertyimage_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["featured_homepage"], name="house_prope_feature_850137_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["is_archived"], name="house_prope_is_arch_4a176b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["price"], name="house_prope_price_437bfc_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["created_at"], name="house_prope_created_21b2dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["deal_type"], name="house_prope_deal_ty_8958f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type"], name="house_prope_propert_6f3867_idx"
            ),
        ),
    ]
