# Generated by Django 5.2 on 2026-06-22 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_property_house_prope_feature_850137_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_property_id', models.PositiveIntegerField(help_text="ID об'єкта в CRM (Realtsoft).")),
                ('crm_url', models.URLField(blank=True, default='', help_text="URL об'єкта в CRM.")),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Оригінальні дані з CRM для історії.')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Синхронізовано'), ('error', 'Помилка'), ('pending', 'Очікує')], default='synced', max_length=20)),
                ('source', models.CharField(choices=[('realtsoft', 'Realtsoft CRM'), ('manual', 'Вручну'), ('import', 'Імпорт')], default='realtsoft', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="ID об'єкта у зовнішній системі.", max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='external_source',
            field=models.CharField(blank=True, choices=[('', 'Власний'), ('realtsoft', 'Realtsoft CRM'), ('import', 'Імпорт')], default='', help_text="Джерело об'єкта.", max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], default='USD', help_text='Валюта ціни.', max_length=3),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['external_source', 'external_id'], name='house_prope_externa_0a39af_idx'),
        ),
        migrations.AddField(
            model_name='externalproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_sources', to='house.property'),
        ),
        migrations.AddIndex(
            model_name='externalproperty',
            index=models.Index(fields=['crm_property_id'], name='house_exter_crm_pro_397e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='externalproperty',
            index=models.Index(fields=['source'], name='house_exter_source_9234f1_idx'),
        ),
        migrations.AddIndex(
            model_name='externalproperty',
            index=models.Index(fields=['last_synced'], name='house_exter_last_sy_bc3fc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalproperty',
            unique_together={('crm_property_id', 'source')},
        ),
    ]
