# Generated by Django 5.2 on 2026-07-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_externalproperty_property_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id', models.PositiveIntegerField(help_text='ID клієнта в CRM', unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('crm_url', models.URLField(blank=True, default='')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='client',
            field=models.ForeignKey(blank=True, help_text="Власник об'єкта з CRM", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='house.client'),
        ),
    ]
