# Generated by Django 5.2 on 2026-07-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_add_client_and_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування додатку',
                'verbose_name_plural': 'Налаштування додатку',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('new_property', "Новий об'єкт"), ('price_changed', 'Зміна ціни'), ('new_inquiry', 'Нова заявка'), ('status_changed', 'Зміна статусу')], max_length=50)),
                ('template', models.TextField(help_text='Шаблон повідомлення. Доступні змінні: {title}, {price}, {address}, {rooms}, {area}, {link}')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон повідомлення',
                'verbose_name_plural': 'Шаблони повідомлень',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
