export const apiEndpoints = {
  csrf: '/api/csrf/',
  properties: '/api/properties/',
  propertyItem: (propertyId) => `/api/properties/${encodeURIComponent(propertyId)}/`,
  propertyBulkAction: '/api/properties/bulk-action/',
  propertiesBySlug: (slug) => `/api/properties/by-slug/${encodeURIComponent(slug)}/`,
  propertyTypes: '/api/property-types/',
  dealTypes: '/api/deal-types/',
  features: '/api/features/',
  highlightSettings: '/api/highlight-settings/',
  propertyImportHtml: '/api/properties/import-html/',
  propertyImportLink: '/api/properties/import-link/',
  propertyImages: (propertyId) => `/api/properties/${encodeURIComponent(propertyId)}/images/`,
  propertyImageDetail: (imageId) => `/api/properties/images/${encodeURIComponent(imageId)}/`,
  propertyImagesReorder: (propertyId) =>
    `/api/properties/${encodeURIComponent(propertyId)}/images/order/`,
  likedProperties: '/api/liked-properties/',
  likeProperty: (propertyId) => `/like/${propertyId}/`,
  toggleFeatured: (propertyId) => `/properties/${propertyId}/toggle-featured/`,
  interactiveMapData: '/test/map/interactive/data/',
  consultation: '/consultation/',
  login: '/login/',
  logout: '/logout/',
  googleAuth: '/accounts/google/login/?process=login',
  appSettings: '/api/settings/',
  realtsoftConnectionTest: '/api/settings/test/realtsoft/',
  telegramTemplates: '/api/telegram-templates/',
  propertyCities: '/api/property-cities/',
  clients: '/api/clients/',
  stats: '/api/stats/',
}
